quotes_project/quotes/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main,name="root"),
    path('<int:page>', views.main,name="root_paginate"),
    path('author/<int:author_id>', views.author_detail, name='author'),
    path('new_author/', views.new_author, name='new_author'),
    path('new_quote/', views.new_quote, name='new_quote'),
]

quotes_project/quotes_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("quotes.urls")),
    path('users/', include("users.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes_project/users/urls.py
from . import views
from django.urls import path,include

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

quotes_project/quotes/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=100)
    born_date = models.CharField(max_length=50)  
    born_location = models.CharField(max_length=150)  
    description = models.TextField()  
    created = models.DateTimeField(auto_now_add=True)

class Tag(models.Model):
    name = models.CharField(max_length=150, null=False, unique=True)

class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None,null=True)
    created = models.DateTimeField(auto_now_add=True)

quotes_project/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)
            

quotes_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Author,Quote

class AuthorForm(ModelForm):

    fullname = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    born_date = CharField(min_length=10, required=True, widget=TextInput())
    born_location = CharField(min_length=10, required=True, widget=TextInput())
    description = CharField(min_length=10, required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname','born_date','born_location', 'description']
        
class QuoteForm(ModelForm):

    quote = CharField(min_length=5, required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['author','tags']

quotes_project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        
        
        
class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']
        
class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

quotes_project/quotes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import Quote, Author, Tag
from .forms import AuthorForm,QuoteForm


def main(request, page = 1):
    quotes = Quote.objects.all()
    
    per_page = 10
    
    paginator = Paginator(list(quotes),per_page)
    quotes_on_page = paginator.page(page)
    
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotes/author.html', {"author": author})

@login_required
def new_author(request):

    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()

            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/new_author.html', {'form': form})

    return render(request, 'quotes/new_author.html', {'form': AuthorForm()})

@login_required
def new_quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            
            # Fix the way you assign the author
            author_name = request.POST.get('author')
            choice_author = Author.objects.filter(fullname=author_name).first()
            if choice_author:
                new_quote.author = choice_author
                new_quote.save()  # Save the quote after assigning the author

            return redirect(to='quotes:root')
        else:
            return render(request, 'quotes/new_quote.html', {"tags": tags, 'authors': authors, 'form': form})

    return render(request, 'quotes/new_quote.html', {"tags": tags, 'authors': authors, 'form': QuoteForm()})

quotes_project/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm, LoginForm, ProfileForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes:root')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotes:root')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotes:root')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotes:root')

@login_required
def profile(request):
    return render(request, 'users/profile.html')

@login_required
def profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:profile')

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'users/profile.html', {'profile_form': profile_form})

quotes_project/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}{% block content %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">{{author.description}}</div>
</div>
{% endblock %}

quotes_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
            content="width=device-width, user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content ie=edge">
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous">'
        {% load static %}
        <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
        <title>Quotes</title>
    </head>

    <body>

        <div class="container">
            <div class="row header-box pt-3">
                <div class="col-md-8">
                    <h1>
                        <a href="/" style="text-decoration: none">Quotes to
                            Scrape</a>
                    </h1>
                </div>
                <div class="col-md-4">
                    <p>
                        {% if user.is_authenticated %}
                        <a href="{% url 'quotes:new_quote' %}"
                            class="btn btn-primary">Add quote</a>
                        <a href="{% url 'quotes:new_author' %}"
                            class="btn btn-primary">Add author</a>
                        <a href="{% url 'users:profile' %}"
                            class="btn btn-primary">Profile</a>
                        <a href="{% url 'users:logout' %}"
                            class="btn btn-primary">Logout</a>
                        {% else %}
                        <a href="{% url 'users:signup' %}"
                            class="btn btn-primary">SignUp</a>
                        <a href="{% url 'users:login' %}"
                            class="btn btn-primary">Login</a>
                        {% endif %}

                    </p>
                </div>
            </div>

            {% block content %} {%endblock%}

        </body>

    </html>

quotes_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author|author_name}}</small>
                <a href="author/{{quote.author|author_id}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{ tag.slug }}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        <nav>
            <ul class="pager">

                <li class="previous">
                    <a
                        class="{%if not quotes.has_previous %} disabled {% endif %}"
                        href="{%if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number%} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span>
                        Previous</a>
                </li>

                <li class="next">
                    <a class="{%if not quotes.has_next %} disabled {% endif %}"
                        href="{%if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number%} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>

    </div>

    {% endblock %}

quotes_project/quotes/templates/quotes/new_author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:new_author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
        <div style="padding: 10px">
        <label> Author born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
            <div style="padding: 10px">
        <label> Author born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes_project/quotes/templates/quotes/new_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:new_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="author">
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes_project/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes_project/users/templates/users/profile.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h1>Profile page: {{user.username}}</h1>
    <img src="{{ user.profile.avatar.url }}" alt="avatar of user"/>
</div>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-md-5">
            <div class="form-group">
                <label class="small mb-1">Change Avatar:</label>
                {{ profile_form.avatar }}
                <span>{{ profile_form.errors.avatar }}</span>
            </div>
        </div>
    </div>
    <div class="grid">
        <button type="submit">Save Changes</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>

{% endblock content %}

quotes_project/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}